#! /bin/bash
# Run Virus Check on Thunderbird Mail #
clear
echo "---------------------------------------------------------"
echo "Check (.cache/thunderbird)... 1 min approx."
echo "---------------------------------------------------------"
clamscan -r --remove /home/timkemp/.cache/thunderbird > /home/timkemp/tlkchkcache.log
echo "---------------------------------------------------------"
echo "Check (.thunderbird)... 3 min approx."
clamscan -r --remove /home/timkemp/.thunderbird > /home/timkemp/tlkchktmb.log
# End
