#!/bin/bash
#----------------------------------------------------------------------#
#
# File: tlkcontomp3
#                                                    
# Desc: Convert $1 files to MP3
#       Assumes music files 
#
# Date: Sept 2016                                                  
#----------------------------------------------------------------------#
clear
#----------------------------------------------------------------------#
# Save Internal Field Seperator, reset at end of script                
#----------------------------------------------------------------------#
# 
wSAVEIFS=$IFS
IFS=$(echo -en "\n\b")
#
#----------------------------------------------------------------------#
echo $1
if [ -z "$1" ];
	then
#
		echo 'Please give a audio file extention as argument.'
#
	else
#
#		Convert music type $1
#	
		for i in *.$1
		do
			if [ -f "$i" ]; then
			rm -f "$i.wav"
			mkfifo "$i.wav"
			mplayer \
			-quiet \
			-vo null \
			-vc dummy \
			-af volume=0,resample=44100:0:1 \
			-ao pcm:waveheader:file="$i.wav" "$i" &
			#echo "---------------------------------------------------------"
			#read -p "Press [Enter] key to Continue..."
			#echo "---------------------------------------------------------"
			#dest=`echo "$i"|sed -e "s/$1$/mp3/"`
			#lame -V0 -h -b 128 --vbr-new "$i.wav" "$dest"
			#rm -f "$i.wav"
			fi
		done
fi
#----------------------------------------------------------------------#
# Reset Internal Field Seperator     
#----------------------------------------------------------------------#
IFS=$wSAVEIFS
